# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a8c9f086364592e8768261eb3312d546052f18600d7a84632723abf1fedfcb676a0869e3cd1896b75a4b12b600fa7373d6f97fd0b14d310beebe4f80252b3d8

test:
  secret_key_base: fc84dcc085edb3bae4d707a10f923fbbb82ff934c0ca2867991422a33e0865993d414699a793f68bc5e68697012699a3205f2b166d3fac9313b95e9b27651c06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
